replicaCount: 1

image:
  repository: facevedo74/scraping-anime
  tag: "aeea33aca6430bfc72e8ab46d65bdd12fcf603b8"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  loadBalancerIP: "172.202.10.115"

env:
  PORT: "3000"

resources:
  requests:
    cpu: "10m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

probes:
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 20
