# Overrides para entorno de producción
replicaCount: 1

image:
  pullPolicy: Always

env:
  PORT: "3000"
  NODE_ENV: "production"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

resources:
  requests:
    cpu: "10m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

service:
  type: LoadBalancer
