# Overrides para entorno de desarrollo
replicaCount: 1

image:
  tag: latest
  pullPolicy: Always

env:
  PORT: "3000"
  NODE_ENV: "development"

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

service:
  type: NodePort
