replicaCount: 2

image:
  repository: facevedo74/scraping-anime
  tag: "7f984e915466dc4306e1a233ed03240af9a5fb2a"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  PORT: "3000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

probes:
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 20
