# Overrides para entorno de desarrollo
replicaCount: 1

image:
  tag: latest
  pullPolicy: Always

env:
  PORT: "3000"
  NODE_ENV: "development"

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "10m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

service:
  type: NodePort
